version: 3.2
orbs:
  node: circleci/node@10.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
workflows:
    build-and-test:
      jobs:
        - build-and-test
